### ISSUE TITLE
Centralizing git?

### ISSUE THREAD

**Issue by bartoszhernas** [beefsack/git-mirror#2]
I don't get this idea, git is distributed system, if you are working with colleagues, you can directly pull/push from them.

Your local copy of repo could behave like mirror, wouldn't it be better to pull all branches to your local repository every 15 minutes if you are really afraid of github failure?

In case center server with git dies, then you can put bare repo into some shared folder (vpn etc) and push pull directly from there using file path as git url. Tried it by putting my repo on NAS in local network.

Its just missing usage of one of greatest features of git...

**Comment by beefsack** [comment]
So far it fits a particular use case we had:
- People working in different time zones, upstream repo updated while some people aren't working.
- Recently we have had intermittent internet outages at the office and it has been troublesome for staff to fetch upstream changes (fetching directly from others with newer versions is what happened.)
- Having a full upstream mirror internally in the office greatly simplified workflow during outages.

Mileage may vary depending on use case, some people would be happy with fetching between developers, some people might want fully fledged remotes using things like Gitorious or Gogs, but for us just needing a simple upstream mirror it's currently working well.

I'll take this as a comment and close the ticket.
